### PR TITLE
Trapping bugs in BugTrap by PVS-Studio!

### PR DESCRIPTION
**Pull request by dimhotepus**
Collection of bugs in BugTrap found by PVS-Studio static analyzer and MSVC compiler.

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
Awesome!

Could you send a pull request with these fixes into [upstream repository](https://github.com/bchavez/BugTrap) so that all BugTrap users can see the fixes?

But don't close this PR yet, if the upstream is no longer maintained (no longer watched by the maintainer, I mean), then we proceed here.

**Comment by dimhotepus** [comment]
> Awesome!
> 
> Could you send a pull request with these fixes into [upstream repository](https://github.com/bchavez/BugTrap) so that all BugTrap users can see the fixes?
> 
> But don't close this PR yet, if the upstream is no longer maintained (no longer watched by the maintainer, I mean), then we proceed here.

https://github.com/bchavez/BugTrap/pull/33

**Comment by dimhotepus** [comment]
> @Xottab-DUTY Well, original repo seems abandoned.
> 
> Suggest to incorporate changes, as we can easily rebase on original repo when somehow original repo accepts pull request.

Ok, original is under review now.

**Comment by bchavez** [comment]
Changes have been merged upstream. Thank you both for the PR and review!

**Comment by dimhotepus** [comment]
Closing, thanks to @bchavez and @Xottab-DUTY upstream is already updated.

**Comment by dimhotepus** [comment]
@Xottab-DUTY Could you, please, integrate upstream changes?

**Comment by Xottab-DUTY** [comment]
@dimhotepus done.

**Pull request closed without merging**
